incarceration_data <- read.csv("https://raw.githubusercontent.com/vera-institute/incarceration-trends/master/incarceration_trends.csv")
library(dplyr)
library(tidyverse)
library(ggplot2)
library(leaflet)
install.packages(maps)
library(maps)
install.packages("usmap")
library(usmap)
